using System.Text;
using eparkapi.Models.Entities;
using eparkapi.Models.Enums;
using Microsoft.EntityFrameworkCore;

namespace eparkapi.Data;

public class EparkDbContext(DbContextOptions<EparkDbContext> options) : DbContext(options)
{
    public DbSet<Role> Roles => Set<Role>();
    public DbSet<Municipality> Municipalities => Set<Municipality>();
    public DbSet<User> Users => Set<User>();
    public DbSet<Zone> Zones => Set<Zone>();
    public DbSet<VehicleType> VehicleTypes => Set<VehicleType>();
    public DbSet<Vehicle> Vehicles => Set<Vehicle>();
    public DbSet<PaymentMethod> PaymentMethods => Set<PaymentMethod>();
    public DbSet<Session> Sessions => Set<Session>();
    public DbSet<SessionExtension> SessionExtensions => Set<SessionExtension>();
    public DbSet<Payment> Payments => Set<Payment>();
    public DbSet<Invoice> Invoices => Set<Invoice>();
    public DbSet<Fine> Fines => Set<Fine>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresEnum<SessionStatus>();
        modelBuilder.HasPostgresEnum<PaymentStatus>();
        modelBuilder.HasPostgresEnum<PaymentReference>();
        modelBuilder.HasPostgresEnum<FineStatus>();

        modelBuilder.Entity<Role>().ToTable("roles");
        modelBuilder.Entity<Municipality>().ToTable("municipalities");
        modelBuilder.Entity<User>().ToTable("users");
        modelBuilder.Entity<Zone>().ToTable("zones");
        modelBuilder.Entity<VehicleType>().ToTable("vehicle_types");
        modelBuilder.Entity<Vehicle>().ToTable("vehicles");
        modelBuilder.Entity<PaymentMethod>().ToTable("payment_methods");
        modelBuilder.Entity<Session>().ToTable("sessions");
        modelBuilder.Entity<SessionExtension>().ToTable("session_extensions");
        modelBuilder.Entity<Payment>().ToTable("payments");
        modelBuilder.Entity<Invoice>().ToTable("invoices");
        modelBuilder.Entity<Fine>().ToTable("fines");

        // Map every property to its snake_case column to match the existing schema.
        foreach (var entity in modelBuilder.Model.GetEntityTypes())
        {
            foreach (var property in entity.GetProperties())
            {
                property.SetColumnName(ToSnakeCase(property.Name));
            }
        }

        // Timestamps are generated by the database (DEFAULT NOW() / updated_at trigger).
        foreach (var name in new[] { "CreatedAt", "UpdatedAt", "IssuedAt", "ExtendedAt" })
        {
            foreach (var entity in modelBuilder.Model.GetEntityTypes())
            {
                var prop = entity.FindProperty(name);
                if (prop is not null)
                {
                    prop.SetDefaultValueSql("NOW()");
                    prop.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.OnAdd;
                }
            }
        }
    }

    private static string ToSnakeCase(string input)
    {
        var sb = new StringBuilder();
        for (var i = 0; i < input.Length; i++)
        {
            var c = input[i];
            if (char.IsUpper(c) && i > 0)
                sb.Append('_');
            sb.Append(char.ToLowerInvariant(c));
        }
        return sb.ToString();
    }
}
